#!/usr/bin/env bash
# debugging nginx port 80
# configure the system links properly
# then restart the service as it was not running
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
