#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.
#script should only display:
#   username
#   user id
#   Home directory path for the user
#while looop

file_name="/etc/passwd"
i=0
lines=0
IFS=':'
if test -f $file_name; then
  lines="$(wc -l < $file_name)"
  fields=('username' 'password' 'user_id' 'group_id' 'user_id_info' 'home_dir' 'command')
  while [[ $i -lt $lines ]]; do
    i="$((i + 1))"
    read -r -a fields < <(tail -n 1 <(head -n $i < $file_name))
    echo "${fields[0]}:${fields[2]}:${fields[5]}"
  done
fi
