#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#   localhost resolves to 127.0.0.2
#   facebook.com resolves to 8.8.8.8.
#   The checker is running on Docker, so make sure to read link

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/host.new /etc/hosts
